apiVersion: v1
kind: Pod 
metadata:
  name: nscout
  namespace: default
spec:
  containers:
  - name: nscout
    image: quay.io/skeeey/nscout:latest
    command: ["/bin/sleep", "3650d"]
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        add:
        - ALL
      privileged: true
      readOnlyRootFilesystem: false
      runAsNonRoot: false
  hostNetwork: true
  nodeSelector:
    your-node-label
